gpytorch.kernelsの使い方

In [7]:
import torch
import gpytorch
x = torch.tensor([[1,0],[0,1]])

In [38]:
# linear kernel : v XTX
covar_module = gpytorch.kernels.LinearKernel()
covar_module.variance = 1.0 # v
covar_x = covar_module(x)
covar_x = covar_x.evaluate()
print(covar_x)

tensor([[1., 0.],
        [0., 1.]], grad_fn=<MmBackward>)


In [39]:
# RBF kernel
covar_module = gpytorch.kernels.RBFKernel()
covar_module.lengthscale = 1.0
covar_x = covar_module(x)
covar_x = covar_x.evaluate()
print(covar_x)

tensor([[1.0000, 0.3679],
        [0.3679, 1.0000]], grad_fn=<RBFCovarianceBackward>)


In [40]:
# 2*RBF
rbf_module = gpytorch.kernels.RBFKernel()
rbf_module.lengthscale = 1.0
first_module = gpytorch.kernels.ScaleKernel(rbf_module)
first_module.outputscale = 2.0

# 3*Linear
lin_module = gpytorch.kernels.LinearKernel()
lin_module.variance = 1.0
second_module = gpytorch.kernels.ScaleKernel(lin_module)
second_module.outputscale = 3.0

# add
covar_module = first_module + second_module
covar_x = covar_module(x)
covar_x = covar_x.evaluate()
print(covar_x)

tensor([[5.0000, 0.7358],
        [0.7358, 5.0000]], grad_fn=<AddBackward0>)
